# Generated by Django 4.2.27 on 2025-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
