# Generated by Django 4.2.27 on 2025-12-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_organizationmember_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="description",
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
