# Generated by Django 4.2.27 on 2025-12-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_remove_organization_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="organizations.organization",
            ),
        ),
    ]
