# Generated by Django 4.2.27 on 2025-12-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_alter_organizationmember_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
