# Generated by Django 4.2.27 on 2025-12-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organization_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
